// #include "entry.h"

// #if defined(ENVIRONMENT_I386) || defined(__i386__) || defined(_M_IX86)
// asm(
//     ".text\n"
//     ".globl ___chkstk_ms\n"
//     ".globl __chkstk_ms\n"
//     "___chkstk_ms:\n"
//     "__chkstk_ms:\n"
//     "    pushl %ecx\n"
//     "    pushl %eax\n"
//     "    leal  0x0c(%esp), %ecx\n"
//     "    cmpl  $0x1000, %eax\n"
//     "    jb    2f\n"
//     "1:\n"
//     "    subl  $0x1000, %ecx\n"
//     "    orl   $0, (%ecx)\n"
//     "    subl  $0x1000, %eax\n"
//     "    cmpl  $0x1000, %eax\n"
//     "    jae   1b\n"
//     "2:\n"
//     "    subl  %eax, %ecx\n"
//     "    orl   $0, (%ecx)\n"
//     "    popl  %eax\n"
//     "    popl  %ecx\n"
//     "    ret\n"
// );
// asm(
//     ".text\n"
//     ".globl __chkstk\n"
//     ".globl _chkstk\n"
//     ".globl ___alloca\n"
//     ".globl __alloca\n"
//     "__chkstk:\n"
//     "_chkstk:\n"
//     "___alloca:\n"
//     "__alloca:\n"
//     "    pushl %ecx\n"
//     "    cmpl  $0x1000, %eax\n"
//     "    leal  0x8(%esp), %ecx\n"
//     "    jb    2f\n"
//     "1:\n"
//     "    subl  $0x1000, %ecx\n"
//     "    testl %ecx, (%ecx)\n"
//     "    subl  $0x1000, %eax\n"
//     "    cmpl  $0x1000, %eax\n"
//     "    ja    1b\n"
//     "2:\n"
//     "    subl  %eax, %ecx\n"
//     "    testl %ecx, (%ecx)\n"
//     "    leal  0x4(%esp), %eax\n"
//     "    movl  %ecx, %esp\n"
//     "    movl  -0x4(%eax), %ecx\n"
//     "    pushl (%eax)\n"
//     "    subl  %esp, %eax\n"
//     "    ret\n"
// );
// #elif defined(ENVIRONMENT_x86_64) || defined(__x86_64__) || defined(_M_X64)
// asm(
//     ".globl __chkstk\n"
//     ".globl ___chkstk_ms\n"
//     "__chkstk:\n"
//     "___chkstk_ms:\n"
//     "   pushq %rcx\n"
//     "   pushq %rax\n"
//     "   cmpq  $0x1000, %rax\n"
//     "   leaq  0x18(%rsp), %rcx\n"
//     "   jb    2f\n"
//     "1:\n"
//     "   subq  $0x1000, %rcx\n"
//     "   orq   $0, (%rcx)\n"
//     "   subq  $0x1000, %rax\n"
//     "   cmpq  $0x1000, %rax\n"
//     "   ja    1b\n"
//     "2:\n"
//     "   subq  %rax, %rcx\n"
//     "   orq   $0, (%rcx)\n"
//     "   popq  %rax\n"
//     "   popq  %rcx\n"
//     "   ret\n"
// );
// #elif defined(ENVIRONMENT_ARM64) || defined(__aarch64__) || defined(_M_ARM64)

// asm(
//     ".globl __chkstk\n"
//     "__chkstk:\n"
//     "   mov  x16, sp\n"
//     "   bfc  x16, #0, #12\n"
//     "1:  sub  x16, x16, #0x1000\n"
//     "   str  xzr, [x16]\n"
//     "   subs x15, x15, #0x1000\n"
//     "   b.hi 1b\n"
//     "   ret\n"
// );
// #endif